package com.example.ahakey.update;

/**
 * Resolves the desktop application version from release metadata.
 *
 * <p>The Windows installer passes {@code -Dapp.version}; ordinary JAR builds
 * fall back to the manifest generated by Maven. Keeping this outside the UI
 * avoids a second hard-coded version that can drift from the release tag.</p>
 */
public final class AppVersion {
    private static final SemanticVersion DEVELOPMENT =
        new SemanticVersion(0, 0, 0);

    private AppVersion() {
    }

    public static SemanticVersion current() {
        String configured = System.getProperty("app.version", "").trim();
        if (!configured.isBlank()) {
            return SemanticVersion.parse(configured);
        }
        Package appPackage = AppVersion.class.getPackage();
        String implementationVersion = appPackage == null
            ? null : appPackage.getImplementationVersion();
        if (implementationVersion != null && !implementationVersion.isBlank()) {
            return SemanticVersion.parse(implementationVersion);
        }
        return DEVELOPMENT;
    }
}
