#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

WIZARD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_ROOT="$(cd "$WIZARD_DIR/.." && pwd)"
NOTARY_PROFILE="AhaKeyNotary"

banner "AhaKey macOS signing + notarization"

stage "Apple Developer account"
say "Developer ID certificates require an active Apple Developer Program team."
say "The Account Holder creates the certificate; the Team ID is shown on the Membership page."
open_url "https://developer.apple.com/account/"
step "Confirm the membership is active and note the 10-character Team ID."
ask APPLE_ID "Apple Account email used for notarization:"
ask APPLE_TEAM_ID "Apple Developer Team ID:"
if [[ -z "$APPLE_ID" || -z "$APPLE_TEAM_ID" ]]; then
  warn "Apple Account email and Team ID are both required."
  exit 1
fi

stage "Developer ID Application certificate"
SIGNING_IDENTITY="$(security find-identity -v -p codesigning 2>/dev/null \
  | grep 'Developer ID Application' | head -n 1 | sed -E 's/.*"(.+)"/\1/' || true)"
if [[ -z "$SIGNING_IDENTITY" ]]; then
  say "No Developer ID Application identity is installed in this Mac's keychain."
  open_url "https://developer.apple.com/account/resources/certificates/list"
  step "Open Keychain Access → Certificate Assistant → Request a Certificate From a Certificate Authority."
  step "Enter your Apple Account email and a common name, choose Saved to disk, and create the CSR."
  step "On Apple's Certificates page click + → Developer ID → Developer ID Application."
  step "Upload the CSR, download the .cer, then double-click it to install it in the login keychain."
  warn "Choose Developer ID Application, not Developer ID Installer."
  pause "Press Enter after the certificate and its private key appear under My Certificates."
  SIGNING_IDENTITY="$(security find-identity -v -p codesigning 2>/dev/null \
    | grep 'Developer ID Application' | head -n 1 | sed -E 's/.*"(.+)"/\1/' || true)"
fi
if [[ -z "$SIGNING_IDENTITY" ]]; then
  warn "Developer ID Application identity is still unavailable; the private key may be missing."
  exit 1
fi
say "Found signing identity: $SIGNING_IDENTITY"
step "In Keychain Access → My Certificates, expand this certificate and confirm a private key is beneath it."
step "Select the certificate, choose File → Export Items, save a password-protected .p12 outside the repository."
if command -v open >/dev/null 2>&1; then open -a "Keychain Access" >/dev/null 2>&1 || true; fi
ask P12_PATH "Absolute path to the exported .p12 file:"
P12_PATH="${P12_PATH/#\~/$HOME}"
if [[ ! -f "$P12_PATH" ]]; then
  warn "P12 file not found: $P12_PATH"
  exit 1
fi
ask_secret P12_PASSWORD "Password used when exporting the .p12:"
if [[ -z "$P12_PASSWORD" ]]; then
  warn "The .p12 export password is required for GitHub Actions."
  exit 1
fi
CERTIFICATE_P12_BASE64="$(base64 < "$P12_PATH" | tr -d '\r\n')"

stage "Notary service password"
say "notarytool requires an app-specific password because Apple Account 2FA is enabled."
open_url "https://account.apple.com/account/manage"
step "Open Sign-In and Security → App-Specific Passwords."
step "Generate a password named AhaKey GitHub Notary, then copy it now; Apple shows it only once."
ask_secret APPLE_APP_SPECIFIC_PASSWORD "Paste the app-specific password:"
if [[ -z "$APPLE_APP_SPECIFIC_PASSWORD" ]]; then
  warn "An app-specific password is required."
  exit 1
fi

stage "Local notarization profile"
say "The credentials will be validated by Apple and stored in your Keychain as $NOTARY_PROFILE."
xcrun notarytool store-credentials "$NOTARY_PROFILE" \
  --apple-id "$APPLE_ID" \
  --team-id "$APPLE_TEAM_ID" \
  --password "$APPLE_APP_SPECIFIC_PASSWORD" \
  --validate
xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null
say "Local notary profile validated. No password was written to the repository."

stage "GitHub Actions secrets"
ask GITHUB_REPOSITORY "GitHub repository [AhakeyAI/desktop]:"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-AhakeyAI/desktop}"
export GH_REPO="$GITHUB_REPOSITORY"
if ! command -v gh >/dev/null 2>&1; then
  warn "GitHub CLI is not installed. Install it, then re-run this wizard."
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  say "GitHub CLI is not authenticated. Complete the browser login now."
  gh auth login --hostname github.com --web
fi
if ! gh repo view "$GITHUB_REPOSITORY" >/dev/null 2>&1; then
  warn "Cannot access GitHub repository $GITHUB_REPOSITORY with the active account."
  exit 1
fi
say "Writing five encrypted Actions secrets to $GITHUB_REPOSITORY."
set_secret MACOS_CERTIFICATE_P12_BASE64 "$CERTIFICATE_P12_BASE64"
set_secret MACOS_CERTIFICATE_PASSWORD "$P12_PASSWORD"
set_secret APPLE_ID "$APPLE_ID"
set_secret APPLE_TEAM_ID "$APPLE_TEAM_ID"
set_secret APPLE_APP_SPECIFIC_PASSWORD "$APPLE_APP_SPECIFIC_PASSWORD"

stage "Build, notarize, and verify locally"
say "This final check builds a Universal 2 DMG, submits it to Apple, staples the ticket, and runs Gatekeeper."
if confirm "Submit a local notarization check to Apple now?"; then
  DMG_BASENAME="AhaKey-Studio-macOS-notarization-check"
  APP_VERSION="0.2.0" \
  NOTARY_PROFILE="$NOTARY_PROFILE" \
  DMG_BASENAME="$DMG_BASENAME" \
    zsh "$WIZARD_DIR/pack-release.sh"
  DMG_PATH="$APP_ROOT/dist/$DMG_BASENAME.dmg"
  xcrun stapler validate "$DMG_PATH"
  spctl --assess --type open --context context:primary-signature -vv "$DMG_PATH"
  say "Local signed and notarized DMG passed Gatekeeper: $DMG_PATH"
else
  SKIPPED+=("local notarization submission and Gatekeeper verification")
fi

finish
