model.enabled=true
model.path=models
model.type=STREAMING_PARAFORMER
tokens.path=tokens.txt
num_threads=4
sample_rate=16000
vad.enabled=false
vad.model.path=silero_vad.onnx
status.poll.period.seconds=5
