# ??????????
# ?????????????????????

# ????????????????
# ???? false ?????????????????????????
# ???? true ?????????????????? AhaType ????????
model.enabled=false

# ?????????????????????
# ????????? models ???
model.path=model_q8.onnx
tokens.path=tokens.txt

# ???? (SENSE_VOICE_SMALL, SENSE_VOICE_MEDIUM, SENSE_VOICE_LARGE)
model.type=SENSE_VOICE_SMALL

# ????
num_threads=4

# ?????????????
sample_rate=16000
n_fft=512
hop_length=160
n_mels=80

feature_dim=560
frames_per_chunk=7

# ???? (0=????, 1=??, 2=??, 3=??, 4=??, 5=??)
language=0

# ?????????
text_norm=0

# ????????????????
status.poll.period.seconds=3