package com.example.ahakey.firmware;

/** Stable, UI-independent error categories for firmware operations. */
public enum FirmwareUpdateError {
    RUNTIME_NOT_FOUND,
    RUNTIME_INVALID,
    HEX_INVALID,
    ISP_NOT_PRESENT,
    UID_QUERY_FAILED,
    UID_EXIT_100,
    CHIP_MISMATCH,
    CHIP_UNKNOWN,
    UAC_CANCELLED,
    PROCESS_OWNERSHIP_INCOMPLETE,
    PROCESS_START_FAILED,
    PROCESS_TIMEOUT,
    FLASH_FAILED,
    POST_FLASH_DEVICE_NOT_RECONNECTED,
    POST_FLASH_VERSION_MISMATCH,
    POST_FLASH_PROTOCOL_MISMATCH,
    POST_FLASH_MODEL_MISMATCH,
    POST_FLASH_CAPABILITIES_MISMATCH,
    CURRENT_VERSION_REQUIRED,
    UNKNOWN_VERSION_CONFIRMATION_REQUIRED,
    DOWNGRADE_CONFIRMATION_REQUIRED,
    CANCELLED,
    BUSY,
    INTERNAL_ERROR
}
