using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Automation;
using System.Windows.Automation.Peers;
using AhaKey.Core;
using AhaKey.Device;
using AhaKey.Services;
using AhaKey.Studio.Controls;
using AhaKey.Studio.ViewModels;
using AhaKey.Studio.Views;
using Microsoft.Extensions.DependencyInjection;
namespace AhaKey.Studio.Services;
public static class KeymapSmokeTest
{
    public static async Task RunAsync(Window window,IServiceProvider services,string output,Action<bool,string> check)
    {
        var vm=services.GetRequiredService<ShellViewModel>();var editor=vm.Keymap;
        window.Width=1360;window.Height=920;
        vm.Profiles.Selected=vm.Profiles.Cards[2];vm.NavigationSelection=vm.Navigation.Single(x=>x.Value==PageId.Keymap);
        vm.Settings.Theme=vm.Settings.Themes.Single(x=>x.Value==ThemeChoice.Light);
        editor.SelectedKey=editor.Keys[1];editor.LocalName="Accept";editor.DeviceLabel="Accept";
        editor.RecordCommand.Execute(null);editor.CaptureKey("Enter",ShortcutModifiers.LeftCtrl);
        await StudioSmokeTest.Settle(window);
        var page=StudioSmokeTest.Descendants(window).OfType<KeymapPage>().Single();
        var device=(DevicePreview)page.FindName("Hardware");var regions=(ListBox)device.FindName("RegionList");
        check(regions.Items.Count==4,"Exactly four interactive physical key regions");
        var k2=(ListBoxItem)regions.ItemContainerGenerator.ContainerFromIndex(1);
        check(AutomationProperties.GetName(k2).Contains("K2") && AutomationProperties.GetName(k2).Contains("Ctrl + Enter"),"Key automation name includes physical key, label and shortcut");
        check(k2.Focus(),"Physical key accepts keyboard focus");
        var next=new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(window),0,Key.Right){RoutedEvent=Keyboard.KeyDownEvent};k2.RaiseEvent(next);
        check(editor.SelectedKey.Key==PhysicalKey.K3,"Arrow navigation selects the next physical key");
        regions.SelectedIndex=1;k2.Focus();
        check(editor.SelectedKey.Key==PhysicalKey.K2,"Physical key selection updates inspector");
        check(ReferenceEquals(editor.SelectedKey,regions.SelectedItem),"Key selection is retained while editing");
        await vm.WriteCommand.ExecuteAsync(null);
        await StudioSmokeTest.Capture(window,output,"keymap-codex-k2-light");
        vm.Settings.Theme=vm.Settings.Themes.Single(x=>x.Value==ThemeChoice.Dark);
        await StudioSmokeTest.Capture(window,output,"keymap-codex-k2-dark");
        foreach(var token in new[]{"KeySelection","KeyHover","Focus","Surface","TextSecondary"}) check(window.TryFindResource(token) is not null,"Dark visual resource "+token);
        editor.RecordCommand.Execute(null);editor.Capture.UpdateModifiers(ShortcutModifiers.RightCtrl);editor.Refresh();
        await StudioSmokeTest.Capture(window,output,"keymap-recording");
        editor.CancelCommand.Execute(null);check(!editor.IsRecording && editor.Session.Action==new KeyboardShortcutAction("Ctrl+Enter"),"Cancel recording preserves existing shortcut");
        editor.RecordCommand.Execute(null);
        var input=new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(window),0,Key.P){RoutedEvent=Keyboard.PreviewKeyDownEvent};window.RaiseEvent(input);
        check(input.Handled && !editor.IsRecording && editor.Session.Action==new KeyboardShortcutAction("P"),"WPF-local capture consumes the event without executing a command");
        window.RaiseEvent(new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(window),0,Key.P){RoutedEvent=Keyboard.PreviewKeyUpEvent});
        editor.RecordCommand.Execute(null);window.RaiseEvent(new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(window),0,Key.Escape){RoutedEvent=Keyboard.PreviewKeyDownEvent});
        check(!editor.IsRecording && editor.Session.Action==new KeyboardShortcutAction("Escape"),"Escape is assigned by WPF-local capture, never used as cancel");
        window.RaiseEvent(new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(window),0,Key.Escape){RoutedEvent=Keyboard.PreviewKeyUpEvent});
        check(editor.ManualKeys.ToHashSet().SetEquals(ShortcutGesture.Keys.Keys),"Manual selector exposes the complete supported HID set");
        editor.ManualKey="F24";editor.SetManualModifier(ShortcutModifiers.RightCtrl,true);editor.SetManualModifier(ShortcutModifiers.LeftAlt,true);
        check(editor.Session.Action==new KeyboardShortcutAction("RightCtrl+Alt+F24") && editor.Chips.SequenceEqual(new[]{"RightCtrl","Alt","F24"}),"Manual side-aware modifiers and F24 update actual draft and chips");
        var manual=(Expander)page.FindName("ManualBuilder");manual.IsExpanded=true;
        window.Width=1024;window.Height=900;manual.BringIntoView();await StudioSmokeTest.Capture(window,output,"completion-manual-shortcut-1024");
        manual.IsExpanded=false;
        editor.RecordCommand.Execute(null);editor.CaptureKey("P",ShortcutModifiers.LeftCtrl|ShortcutModifiers.LeftShift);
        editor.Advanced=true;await StudioSmokeTest.Settle(window);((Expander)page.FindName("AdvancedPanel")).BringIntoView();await StudioSmokeTest.Capture(window,output,"keymap-advanced");
        var advanced=(Expander)page.FindName("AdvancedPanel");
        check(StudioSmokeTest.Descendants(advanced).OfType<TextBox>().All(x=>x.IsReadOnly),"Advanced HID and encoded bytes are read-only");
        editor.Advanced=false;StudioSmokeTest.Descendants(window).OfType<ScrollViewer>().First(x=>x.Content is Grid).ScrollToTop();editor.SelectedKey=editor.Keys[0];((ListBoxItem)regions.ItemContainerGenerator.ContainerFromIndex(0)).Focus();
        check(!editor.RecordCommand.CanExecute(null) && !editor.ClearCommand.CanExecute(null),"K1 inspector rejects arbitrary editing");
        await StudioSmokeTest.Capture(window,output,"keymap-k1");editor.SelectedKey=editor.Keys[1];k2.Focus();
        check(vm.Profiles.Cards[2].IsDirty && vm.SyncLabel==vm.L["UnsavedChanges"],"Edited profile has a subtle dirty indicator");
        await StudioSmokeTest.Capture(window,output,"keymap-unsaved");
        editor.LocalName="Принять ответ 接受";check(editor.LocalName=="Принять ответ 接受","Unicode local name is preserved");
        var label=(TextBox)page.FindName("DeviceLabelInput");label.Text="Принять";label.GetBindingExpression(TextBox.TextProperty).UpdateSource();
        check(editor.LabelInvalid && !vm.CanWrite && editor.DeviceLabel=="Принять","Invalid ASCII label remains visible and blocks writing");
        vm.Profiles.Selected=vm.Profiles.Cards[0];check(!editor.LabelInvalid && !vm.CanWrite,"Invalid label in another profile still blocks a whole-configuration write");
        vm.Profiles.Selected=vm.Profiles.Cards[2];check(editor.DeviceLabel=="Принять","Invalid label draft survives switching profiles");
        editor.DeviceLabel="12345678901234567890";check(!editor.LabelInvalid,"20-character device label accepted");
        editor.DeviceLabel="123456789012345678901";check(editor.LabelInvalid,"21-character device label rejected without truncation");editor.DeviceLabel="Accept";
        var state=vm.Manager.Tracker.State;editor.TestCommand.Execute(null);check(vm.Manager.Tracker.State==state && editor.Feedback!.Contains(vm.L["WouldSend"]),"Simulation Test action leaves sync state unchanged");
        vm.Profiles.Selected=vm.Profiles.Cards[0];check(editor.Session.Action is DisabledAction,"Other profile configuration remains independent");vm.Profiles.Selected=vm.Profiles.Cards[2];
        editor.RecordCommand.Execute(null);vm.OpenSettingsCommand.Execute(null);check(!editor.IsRecording,"Leaving Keymap releases shortcut capture");
        vm.NavigationSelection=vm.Navigation.Single(x=>x.Value==PageId.Keymap);check(editor.Session.Action==new KeyboardShortcutAction("Ctrl+Shift+P"),"Page and profile switching preserve key drafts");
        await vm.WriteCommand.ExecuteAsync(null);check(vm.Manager.Tracker.State==SyncState.Synced && !vm.Profiles.Cards[2].IsDirty,"Mock write verifies readback and clears dirty indicator");
        await StudioSmokeTest.Capture(window,output,"keymap-write-success");
        editor.RecordCommand.Execute(null);editor.CaptureKey("Enter",ShortcutModifiers.RightCtrl);var writing=vm.WriteCommand.ExecuteAsync(null);
        editor.RecordCommand.Execute(null);editor.CaptureKey("D",ShortcutModifiers.LeftCtrl);await writing;
        check(vm.Manager.Tracker.State==SyncState.UnsavedChanges && editor.Session.Action==new KeyboardShortcutAction("Ctrl+D"),"Keymap edit during older write survives completion");
        vm.Failure=vm.Failures.Single(x=>x.Value==MockFailure.WriteFailure);vm.ArmFailureCommand.Execute(null);await vm.WriteCommand.ExecuteAsync(null);
        check(vm.Manager.Tracker.State==SyncState.WriteFailed && editor.Session.Action==new KeyboardShortcutAction("Ctrl+D"),"Mock write failure retains editor draft");
        await StudioSmokeTest.Capture(window,output,"keymap-write-failure");
        await vm.DisconnectCommand.ExecuteAsync(null);await vm.ConnectCommand.ExecuteAsync(null);
        vm.Failure=vm.Failures.Single(x=>x.Value==MockFailure.Timeout);vm.ArmFailureCommand.Execute(null);await vm.WriteCommand.ExecuteAsync(null);
        check(vm.Manager.Tracker.State==SyncState.Indeterminate,"Mock timeout remains indeterminate");
        await StudioSmokeTest.Capture(window,output,"keymap-indeterminate");
        await vm.DisconnectCommand.ExecuteAsync(null);await vm.ConnectCommand.ExecuteAsync(null);await vm.WriteCommand.ExecuteAsync(null);
        foreach(var lang in new[]{LanguageChoice.Russian,LanguageChoice.Chinese})
        {vm.Settings.Language=vm.Settings.Languages.Single(x=>x.Value==lang);await StudioSmokeTest.Capture(window,output,lang==LanguageChoice.Russian?"keymap-ru":"keymap-zh");}
        vm.Settings.Language=vm.Settings.Languages.Single(x=>x.Value==LanguageChoice.English);vm.Settings.Theme=vm.Settings.Themes.Single(x=>x.Value==ThemeChoice.Light);
        foreach(var token in new[]{"KeySelection","KeyHover","Focus","Surface","TextSecondary"}) check(window.TryFindResource(token) is not null,"Light visual resource "+token);
        window.Width=1024;window.Height=900;await StudioSmokeTest.Capture(window,output,"keymap-1024");
        var inspector=(Border)page.FindName("Inspector");check(inspector.ActualWidth>=360 && page.ActualWidth<=window.ActualWidth-212,"1024 DIP layout keeps inspector and photo within content width");
        check(LocalShortcutInput.Name(Key.OemPlus)=="Equal" && LocalShortcutInput.Name(Key.RightCtrl) is null && LocalShortcutInput.IsModifier(Key.RightCtrl),"WPF key mapping separates physical modifier sides");
        editor.RecordCommand.Execute(null);page.RaiseEvent(new RoutedEventArgs(FrameworkElement.UnloadedEvent,page));check(!editor.IsRecording,"Unloading editor releases shortcut capture");
    }
}
