<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk"/><PackageReference Include="xunit"/><PackageReference Include="xunit.runner.visualstudio"><PrivateAssets>all</PrivateAssets></PackageReference><ProjectReference Include="../../src/AhaKey.Firmware/AhaKey.Firmware.csproj"/><ProjectReference Include="../../src/AhaKey.Core/AhaKey.Core.csproj"/><ProjectReference Include="../../src/AhaKey.Services/AhaKey.Services.csproj"/></ItemGroup><ItemGroup><Using Include="Xunit"/></ItemGroup><ItemGroup><None Update="Fixtures/*.json" CopyToOutputDirectory="PreserveNewest"/></ItemGroup></Project>